### ISSUE TITLE
exaple_simulator_2d/3d doesn't work

### ISSUE THREAD

**Issue by piotrbartman** [KOS-UJ/conmech#53]
@michalJur 

```
Traceback (most recent call last):
  File "/Users/prb/PycharmProjects/conmech/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-947d82794ef2>", line 1, in <module>
    runfile('/Users/prb/PycharmProjects/conmech/examples/example_simulator_3d.py', wdir='/Users/prb/PycharmProjects/conmech/examples')
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/prb/PycharmProjects/conmech/examples/example_simulator_3d.py", line 5, in <module>
    from deep_conmech.graph.helpers import thh
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "<fstring>", line 1
    (data=)
         ^
SyntaxError: invalid syntax
```

**Comment by piotrbartman** [comment]
#54 @michalJur 

```
Traceback (most recent call last):
  File "/Users/prb/PycharmProjects/conmech/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4c6c75f31c38>", line 1, in <module>
    runfile('/Users/prb/PycharmProjects/conmech/examples/examples_roll.py', wdir='/Users/prb/PycharmProjects/conmech/examples')
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/prb/PycharmProjects/conmech/examples/examples_roll.py", line 4, in <module>
    from deep_conmech.common.plotter import plotter_mapper
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/prb/PycharmProjects/conmech/deep_conmech/common/plotter/plotter_mapper.py", line 8, in <module>
    from deep_conmech.common.plotter.plotter_2d import Plotter
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/prb/PycharmProjects/conmech/deep_conmech/common/plotter/plotter_2d.py", line 5, in <module>
    import imageio
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'imageio'
```

**Comment by michalJur** [comment]
imageio is used for animations - I will probably remove it (and change to built-in matplotlib function) or add to dependencies

**Comment by piotrbartman** [comment]
I think for now it should go to requirements.txt

**Comment by michalJur** [comment]
I replaced imageio - please check if it works now
